# Generated by Django 3.2.7 on 2021-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Время написания')),
                ('name', models.CharField(default='***', max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(default='Я опять забыл написать текст :(', max_length=1024, verbose_name='Текст')),
                ('slug', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Slug (не трогать)')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Никнейм')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Реальные имя и фамилия')),
                ('password', models.CharField(default='123123', max_length=100, verbose_name='Пароль')),
                ('permissions', models.IntegerField(default=0, verbose_name='Возможности')),
                ('slug', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Slug (не трогать)')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
    ]
